In [1]:
# initialization

from slnm import gather 

lst = ["Tbilisi","Bogota"]
case = "მინიმალური"
gather(lst)

# pip install -r requirements.txt

ModuleNotFoundError: No module named 'webdriver_manager'

In [ ]:

import pandas as pd
places_data = {}
for place in lst:   
    df = pd.read_excel(f"{place}_data.xlsx")   
    df = df.rename(columns={"Unnamed: 0":"ინდექსი"})
    df = df.set_index("ინდექსი")
    df = df.ffill()
    df["რეალური საშუალო"] = round(df["მინიმალური"]+( df["მაქსიმალური"] - df["მინიმალური"] )  /2 , 2)  

    places_data[place] = df

# df = pd.concat(places_data.values(), axis=1,keys = places_data.keys())
df = pd.concat(places_data.values(), axis=1, keys = [lst[0],lst[1]])
df["difference"] = df[lst[1]][case] - df[lst[0]][case]
df

                                                   Tbilisi            \
                                                    სახელი   საშუალო
ინდექსი
0                             Meal, Inexpensive Restaurant     25.50
1        Meal for 2 People, Mid-range Restaurant, Three...    100.00
2           McMeal at McDonalds (or Equivalent Combo Meal)     20.00
3                        Domestic Beer (0.5 liter draught)      5.00
4                        Imported Beer (0.33 liter bottle)      7.00
5                                     Cappuccino (regular)      7.01
6                           Coke/Pepsi (0.33 liter bottle)      2.32
7                                Water (0.33 liter bottle)      1.24
8                                Milk (regular), (1 liter)      4.56
9                         Loaf of Fresh White Bread (500g)      1.61
10                                     Rice (white), (1kg)      5.96
11                                     Eggs (regular) (12)      6.46
12                                      Local Cheese (1kg)     20.42
13                                   Chicken Fillets (1kg)     17.27
14       Beef Round (1kg) (or Equivalent Back Leg Red M...     25.53
15                                            Apples (1kg)      3.41
16                                            Banana (1kg)      4.41
17                                           Oranges (1kg)      4.27
18                                            Tomato (1kg)      3.75
19                                            Potato (1kg)      2.05
20                                             Onion (1kg)      1.77
21                                        Lettuce (1 head)      2.86
22                                Water (1.5 liter bottle)      1.68
23                              Bottle of Wine (Mid-Range)     15.00
24                        Domestic Beer (0.5 liter bottle)      3.47
25                       Imported Beer (0.33 liter bottle)      5.16
26                           Cigarettes 20 Pack (Marlboro)      7.90
27                        One-way Ticket (Local Transport)      1.00
28                            Monthly Pass (Regular Price)     40.00
29                              Taxi Start (Normal Tariff)      4.00
30                                Taxi 1km (Normal Tariff)      2.00
31                      Taxi 1hour Waiting (Normal Tariff)     12.00
32                                      Gasoline (1 liter)      3.85
33       Volkswagen Golf 1.4 90 KW Trendline (Or Equiva...  50000.00
34       Toyota Corolla Sedan 1.6l 97kW Comfort (Or Equ...  56566.67
35       Basic (Electricity, Heating, Cooling, Water, G...    209.43
36       1 min. of Prepaid Mobile Tariff Local (No Disc...      0.23
37       Internet (60 Mbps or More, Unlimited Data, Cab...     54.97
38                   Fitness Club, Monthly Fee for 1 Adult    135.53
39                   Tennis Court Rent (1 Hour on Weekend)     37.39
40                   Cinema, International Release, 1 Seat     17.00
41       Preschool (or Kindergarten), Full Day, Private...    583.33
42        International Primary School, Yearly for 1 Child  14313.44
43                  1 Pair of Jeans (Levis 501 Or Similar)    252.47
44        1 Summer Dress in a Chain Store (Zara, H&M, ...)    122.23
45                1 Pair of Nike Running Shoes (Mid-Range)    322.26
46                    1 Pair of Men Leather Business Shoes    423.68
47                    Apartment (1 bedroom) in City Centre   2110.67
48                 Apartment (1 bedroom) Outside of Centre   1416.50
49                   Apartment (3 bedrooms) in City Centre   3902.96
50                Apartment (3 bedrooms) Outside of Centre   2495.72
51       Price per Square Meter to Buy Apartment in Cit...   4903.43
52       Price per Square Meter to Buy Apartment Outsid...   2546.78
53       Mortgage Interest Rate in Percentages (%), Yea...     12.25

                                                \
        მინიმალური მაქსიმალური რეალური საშუალო
ინდექსი
0            15.00       40.00           27.50
1            70.00      150.00          110.00
2            17.00       23.00           20.00
3             3.00        8.00            5.50
4             5.00       11.00            8.00
5             4.00       10.00            7.00
6             1.50        3.50            2.50
7             0.90        2.00            1.45
8             3.50        5.40            4.45
9             1.00        3.00            2.00
10            3.00        8.00            5.50
11            4.80        8.40            6.60
12           14.00       32.00           23.00
13           10.00       20.00           15.00
14           20.00       30.00           25.00
15            2.00        5.00            3.50
16            3.50        7.00            5.25
17            2.89        7.00            4.94
18            1.90        7.00            4.45
19            1.00        3.00            2.00
20            1.00        2.75            1.88
21            1.50        4.00            2.75
22            1.00        2.00            1.50
23           10.00       25.00           17.50
24            3.00        5.00            4.00
25            3.60        7.00            5.30
26            7.00        9.00            8.00
27            1.00        1.00            1.00
28           30.00       40.00           35.00
29            2.50        6.00            4.25
30            0.94        3.00            1.97
31            6.00       18.00           12.00
32            3.50        4.00            3.75
33        50000.00    60000.00        55000.00
34        52400.00    60000.00        56200.00
35          120.00      310.00          215.00
36            0.10        0.30            0.20
37           40.00       80.00           60.00
38           80.00      200.00          140.00
39           20.00       50.00           35.00
40           14.00       22.00           18.00
41          350.00      800.00          575.00
42         5000.00    28000.00        16500.00
43           80.00      400.00          240.00
44           60.00      199.00          129.50
45          150.00      400.00          275.00
46          200.00      650.00          425.00
47         1422.00     3008.50         2215.25
48          957.25     2188.00         1572.62
49         2735.00     6000.00         4367.50
50         1914.50     4102.50         3008.50
51         3200.00     6800.00         5000.00
52         1914.50     3500.00         2707.25
53            8.50       18.00           13.25

                                                    Bogota            \
                                                    სახელი   საშუალო
ინდექსი
0                             Meal, Inexpensive Restaurant      8.22
1        Meal for 2 People, Mid-range Restaurant, Three...     49.30
2           McMeal at McDonalds (or Equivalent Combo Meal)     12.05
3                        Domestic Beer (0.5 liter draught)      2.74
4                        Imported Beer (0.33 liter bottle)      5.48
5                                     Cappuccino (regular)      2.93
6                           Coke/Pepsi (0.33 liter bottle)      1.52
7                                Water (0.33 liter bottle)      1.27
8                                Milk (regular), (1 liter)      2.26
9                         Loaf of Fresh White Bread (500g)      2.50
10                                     Rice (white), (1kg)      2.12
11                                     Eggs (regular) (12)      3.95
12                                      Local Cheese (1kg)     10.70
13                                   Chicken Fillets (1kg)      9.64
14       Beef Round (1kg) (or Equivalent Back Leg Red M...     14.05
15                                            Apples (1kg)      5.02
16                                            Banana (1kg)      1.99
17                                           Oranges (1kg)      2.43
18                                            Tomato (1kg)      2.38
19                                            Potato (1kg)      2.05
20                                             Onion (1kg)      1.91
21                                        Lettuce (1 head)      1.44
22                                Water (1.5 liter bottle)      1.49
23                              Bottle of Wine (Mid-Range)     21.91
24                        Domestic Beer (0.5 liter bottle)      1.89
25                       Imported Beer (0.33 liter bottle)      3.39
26                           Cigarettes 20 Pack (Marlboro)      4.38
27                        One-way Ticket (Local Transport)      1.45
28                            Monthly Pass (Regular Price)     69.84
29                              Taxi Start (Normal Tariff)      2.74
30                                Taxi 1km (Normal Tariff)      3.83
31                      Taxi 1hour Waiting (Normal Tariff)     13.69
32                                      Gasoline (1 liter)      1.34
33       Volkswagen Golf 1.4 90 KW Trendline (Or Equiva...  30673.30
34       Toyota Corolla Sedan 1.6l 97kW Comfort (Or Equ...  46248.21
35       Basic (Electricity, Heating, Cooling, Water, G...    178.25
36       1 min. of Prepaid Mobile Tariff Local (No Disc...      0.15
37       Internet (60 Mbps or More, Unlimited Data, Cab...     51.95
38                   Fitness Club, Monthly Fee for 1 Adult     44.16
39                   Tennis Court Rent (1 Hour on Weekend)     21.74
40                   Cinema, International Release, 1 Seat      8.49
41       Preschool (or Kindergarten), Full Day, Private...    557.19
42        International Primary School, Yearly for 1 Child  12011.56
43                  1 Pair of Jeans (Levis 501 Or Similar)    102.50
44        1 Summer Dress in a Chain Store (Zara, H&M, ...)     77.36
45                1 Pair of Nike Running Shoes (Mid-Range)    158.55
46                    1 Pair of Men Leather Business Shoes    145.46
47                    Apartment (1 bedroom) in City Centre    871.97
48                 Apartment (1 bedroom) Outside of Centre    670.98
49                   Apartment (3 bedrooms) in City Centre   1593.75
50                Apartment (3 bedrooms) Outside of Centre   1249.90
51       Price per Square Meter to Buy Apartment in Cit...   3770.19
52       Price per Square Meter to Buy Apartment Outsid...   3053.88
53       Mortgage Interest Rate in Percentages (%), Yea...     11.60

                                               difference
        მინიმალური მაქსიმალური რეალური საშუალო
ინდექსი
0             5.48       13.69            9.59      -9.52
1            32.86       87.64           60.25     -37.14
2            10.95       13.69           12.32      -6.05
3             1.42        5.42            3.42      -1.58
4             3.83        8.22            6.02      -1.17
5             1.64        4.38            3.01      -2.36
6             1.10        2.46            1.78      -0.40
7             1.10        2.19            1.64       0.20
8             1.64        2.95            2.30      -1.86
9             1.10        3.62            2.36       0.10
10            1.33        3.02            2.17      -1.67
11            2.90        5.23            4.07      -1.90
12            4.38       21.91           13.14      -9.62
13            6.57       13.69           10.13      -3.43
14            7.67       20.20           13.93     -12.33
15            2.42        8.22            5.32       0.42
16            1.10        5.48            3.29      -2.40
17            1.10        6.03            3.56      -1.79
18            0.82        3.83            2.33      -1.08
19            0.82        3.94            2.38      -0.18
20            0.82        3.34            2.08      -0.18
21            0.71        2.46            1.58      -0.79
22            0.82        2.19            1.50      -0.18
23           10.95       32.86           21.90       0.95
24            1.10        2.74            1.92      -1.90
25            1.64        5.54            3.59      -1.96
26            3.29        6.03            4.66      -3.71
27            1.37        1.48            1.42       0.37
28           54.77       95.26           75.02      24.77
29            2.19        4.38            3.28      -0.31
30            2.74        5.48            4.11       1.80
31            8.38       16.43           12.40       2.38
32            1.30        1.45            1.38      -2.20
33        24916.58    38341.62        31629.10  -25083.42
34        38341.62    54773.74        46557.68  -14058.38
35          109.55      325.90          217.72     -10.45
36            0.05        0.27            0.16      -0.05
37           41.08       76.68           58.88       1.08
38           27.39       65.73           46.56     -52.61
39           10.95       32.86           21.90      -9.05
40            6.57       13.69           10.13      -7.43
41          273.87     1095.47          684.67     -76.13
42         5477.37    19718.55        12597.96     477.37
43           49.30      166.51          107.90     -30.70
44           32.86      164.32           98.59     -27.14
45          109.55      246.48          178.02     -40.45
46           82.16      219.09          150.62    -117.84
47          657.28     1369.34         1013.31    -764.72
48          438.19      985.93          712.06    -519.06
49         1095.47     2738.69         1917.08   -1639.53
50          821.61     2179.65         1500.63   -1092.89
51         2464.82     4929.64         3697.23    -735.18
52         2464.82     3834.16         3149.49     550.32
53            9.00       15.00           12.00       0.50

In [ ]:


def is_True(num):
    if str(num)[0] == "-":
        return 'background-color: lime'
    
def is_False(num):
    if str(num)[0] != "-":
        return 'background-color: red'
df = df.style.applymap(is_True, subset=['difference'])
df = df.applymap(is_False, subset=['difference'])
df.to_excel("result.xlsx")